keys:
  - &zine_desktop age12vugtyl2fwzjv8zay6muqlnrgc0qgt0evwgprm25ktfv8rutz9vstzapve
  - &aliyun-01 age1nt3n3qns256x4z6v9q0lp8n56nczj63ynft65nss7elcyy2p9ptsa5cqnp

creation_rules:
  - path_regex: ^secrets/gnupg\.yaml$
    key_groups:
      - age:
          - *zine_desktop
  - path_regex: ^secrets/aliyun-01\.yaml$
    key_groups:
      - age:
          - *zine_desktop
          - *aliyun-01
  - path_regex: ^secrets/ssh-hosts\.yaml$
    key_groups:
      - age:
          - *zine_desktop
