keys:
  - &zine_desktop age12vugtyl2fwzjv8zay6muqlnrgc0qgt0evwgprm25ktfv8rutz9vstzapve
  # TODO: 在 aliyun-01 上运行 `ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub` 后替换下面的占位符
  # - &aliyun-01 age1...

creation_rules:
  - path_regex: ^secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *zine_desktop
          # - *aliyun-01
