cursor #181c1f
cursor_text_color #41484d

foreground            #181c1f
background            #f6fafe
selection_foreground  #ffffff
selection_background  #b6c9d8
url_color             #1f6586

color0   #0f1417
color1   #7f092f
color2   #00640b
color3   #a09700
color4   #1b688c
color5   #b2daed
color6   #1f6586
color7   #232425
color8   #6d7071
color9   #be4364
color10  #169324
color11  #aea300
color12  #2376a1
color13  #b2daed
color14  #6b98ae
color15  #c2c7c9
