# Helpers for explicit in-store vs out-of-store symlinks.
#
# Use these in program modules so the choice of linking strategy is visible
# at the seam, not hidden in a bare `source = df "..."` call.
{ config }:

let
  # Absolute path to this dotfiles repository.
  # Used for out-of-store symlinks to native config directories that are
  # edited frequently (e.g. Neovim, Emacs), so changes take effect without
  # re-running nixos-rebuild.
  # See: https://nixos-and-flakes.thiscute.world/best-practices/accelerating-dotfiles-debugging
  dotfilesDir = "${config.home.homeDirectory}/.config/home-manager";

  mkOutOfStore = target: config.lib.file.mkOutOfStoreSymlink target;
in
{
  # Link into the Nix store (default Home Manager behaviour for `source`).
  mkInStore = path: path;

  # Link directly to an absolute path outside the Nix store.
  # Required when the target is managed by the host system and must not be
  # copied into /nix/store (e.g. system-wide fontconfig files).
  inherit mkOutOfStore;

  # Link directly to a path inside this dotfiles repository.
  # Use this for native config files that are edited frequently and do not
  # need to be generated by Nix; changes are visible immediately.
  mkOutOfStoreDotfiles = relPath: mkOutOfStore "${dotfilesDir}/${relPath}";
}
